import time

from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

#need window id to switch to other tabs, Id's are dynamic which are generated by browser itself
#can be found from current_window_handle returns ID of single browser window
#window_handles return Window ID's of multiple browser windows
class BrowserWindows():
    def BrowserWindow1(self):

        driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")

        #returns id of single window
        # windowId1 = driver.current_window_handle
        # print(windowId1)
        time.sleep(5)
        driver.find_element(By.LINK_TEXT, "OrangeHRM, Inc").click()
        windowIDs = driver.window_handles

        # parentWindowID = windowIDs[0]
        # childWindowID = windowIDs[1]
        # # print(windowIDs[0]) #returns parent ID
        # # print(windowIDs[1]) #child window ID
        #
        # driver.switch_to.window(childWindowID)
        # print("Child window id", driver.title)
        #
        # driver.switch_to.window(parentWindowID)
        # print("parent window id", driver.title)

        #to get ids of all windows
        for i in windowIDs:
            driver.switch_to.window(i)
            print(driver.title)

        #to close specific windows
        for i in windowIDs:
            driver.switch_to.window(i)
            if driver.title == "OrangeHRM":
                driver.close() #parent window closed



objWin = BrowserWindows()
objWin.BrowserWindow1()